server:
  port: 10084 
  error:
    include-message: always    
spring:
  application:
      name: commerce-trading-center
  main:
    allow-bean-definition-overriding: true
  webflux:
    base-path: /commerce-trading-center
  redis:
    host: 172.20.111.176
    port: 6379
    timeout: 5000
  r2dbc:
    url: r2dbc:pool:postgres://172.20.111.176:5432/commerce_db
    username: postgres
    password: postgres
  # For Rabbit Listener  
  rabbitmq:
    host: 172.20.111.176
    port: 5672
