apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
## 請將IP Range修改成當前網段。
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.78.50-192.168.78.150