# RabbitMQ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-rabbit
  labels:
    app: commerce-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce-rabbit
  template:
    metadata:
      labels:
        app: commerce-rabbit
    spec:
      containers:
        - name: commerce-rabbit
          image: rabbitmq:3.8.3-management
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          envFrom:
            - configMapRef:
                name: rabbit-config
          volumeMounts:
            - mountPath: /var/log/rabbitmq
              name: rabbit-logs
      volumes:
        - name: rabbit-logs
          persistentVolumeClaim:
            claimName: rabbit-pv-claim
---
# RabbitMQ Service
apiVersion: v1
kind: Service
metadata:
  name: commerce-rabbit
  labels:
    app: commerce-rabbit
spec:
  type: NodePort
  ports:
    - port: 5672
      targetPort: 5672
      nodePort: 30672
      name: tcp-5672
    - port: 15672
      targetPort: 15672
      nodePort: 30673
      name: tcp-15672
  selector:
    app: commerce-rabbit
