apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-configmap-sql
  labels:
    app: commerce-postgres
data:
  V1__create_customer_data.sql: |
    INSERT INTO cloud.customer
    (customer_id, "name", email, "password", enabled, from_ip, create_time, modify_time, create_by, modify_by)
    VALUES('tony01', 'NO NAME', 'tony01@gmail.com', '123456', true, 'localhost', NOW(), NULL, 'tony01', 'tony01');
    INSERT INTO cloud.customer
    (customer_id, "name", email, "password", enabled, from_ip, create_time, modify_time, create_by, modify_by)
    VALUES('tony02', 'Tony.su', 'tony02@gmail.com', NULL, true, 'localhost', NOW(), NULL, 'tony02', NULL);
    INSERT INTO cloud.customer
    (customer_id, "name", email, "password", enabled, from_ip, create_time, modify_time, create_by, modify_by)
    VALUES('tony03', 'Tony.su', 'tony03@gmail.com', NULL, true, 'localhost', NOW(), NULL, 'tony03', NULL);
