apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration-job
  labels:
    app: commerce-postgres
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway:7.9.1
          command:
            [
              "flyway",
              "-configFiles=/flyway/conf/flyway.config",
              "-locations=filesystem:/flyway/sql",
              "-connectRetries=60",
              "migrate",
            ]
          volumeMounts:
            - mountPath: /flyway/sql
              name: flyway-sql
            - mountPath: /flyway/conf
              name: flyway-conf
      volumes:
        - name: flyway-sql
          configMap:
            name: migration-configmap-sql
        - name: flyway-conf
          configMap:
            name: migration-configmap-config
      restartPolicy: Never
  backoffLimit: 1
