apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-configmap-config
  labels:
    app: commerce-postgres
data:
  flyway.config: |
    flyway.url=jdbc:postgresql://commerce-postgres:5432/commerce_db
    flyway.user=postgres
    flyway.password=postgres
    flyway.baselineOnMigrate=false
