server:
  port: 10078  
  error:
    include-message: always  
spring:
  application:
      name: commerce-client
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILE_ACTIVE:local}
  webflux:
    base-path: /commerce-client

## 自定義            
commerce:
  secret:
    client-id: clientapp
    client-secret: 123
    