server:
  port: 10078  
  error:
    include-message: always  
spring:
  application:
      name: commerce-client
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILE_ACTIVE:local}
  webflux:
    base-path: /commerce-client

## 自定義            
# Oauth Client
commerce:
  secret:
    client-id: clientapp
    client-secret: 123
# 分散式ID生成設定
snowflake:
  datacenter-id: ${DATACENTER_ID:1}
  worker-id: ${WORKER_ID:1}
