apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-biz-product-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce-biz-product
      version: v1
  template:
    metadata:
      labels:
        app: commerce-biz-product
        version: v1
    spec:
      containers:
        - name: commerce-biz-product
          image: commerce-biz-product:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10082
          env:
            - name: VERSION
              value: "v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-biz-product-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce-biz-product
      version: v2
  template:
    metadata:
      labels:
        app: commerce-biz-product
        version: v2
    spec:
      containers:
        - name: commerce-biz-product
          image: commerce-biz-product:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10082
          env:
            - name: VERSION
              value: "v2"
---
apiVersion: v1
kind: Service
metadata:
  name: commerce-biz-product
  labels:
    app: commerce-biz-product
spec:
  type: ClusterIP
  ports:
  - port: 10082
    name: http
  selector:
    app: commerce-biz-product