version: "3.7"
services:
  commerce-rabbit:
    image: rabbitmq:3.8.3-management
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    volumes:
      - rabbitmq_logs:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    ports:
      - 30672:5672
      - 30673:15672
    networks:
      - rabbit_network

volumes:
  rabbitmq_logs:

networks:
  rabbit_network: