server:
  port: 10082 
  error:
    include-message: always    
spring:
  application:
      name: commerce-biz-product
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILE_ACTIVE:local}
  webflux:
    base-path: /api
  redis:
    host: commerce-redis
    port: 6379
    timeout: 5000
  r2dbc:
    url: r2dbc:pool:postgres://commerce-postgres:5432/commerce_db
    username: postgres
    password: postgres
  # For Rabbit Listener  
  rabbitmq:
    host: commerce-rabbit
    port: 5672
  cloud:
    # Stream
    stream:
      bindings:
        # product-consumer (only one server can consumer)
        product-in:
          destination: product
          group: group
          contentType: application/json
          consumer:
            max-attempts: 3
      # dlx/dlq setup
      rabbit:
        bindings:
          product-in:
            consumer:
              expires: 3600000
              ttl: 5000
              auto-bind-dlq: true
              dlq-ttl: 5000
