apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-trading-center-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce-trading-center
      version: v1
  template:
    metadata:
      labels:
        app: commerce-trading-center
        version: v1
    spec:
      containers:
        - name: commerce-trading-center
          image: commerce-trading-center:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10084
          env:
            - name: VERSION
              value: "v1"
---
apiVersion: v1
kind: Service
metadata:
  name: commerce-trading-center
  labels:
    app: commerce-trading-center
spec:
  type: ClusterIP
  ports:
  - port: 10084
    name: http
  selector:
    app: commerce-trading-center