server:
  port: 10080 
  error:
    include-message: always    
spring:
  application:
      name: commerce-biz-order
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILE_ACTIVE:local}
  webflux:
    base-path: /api