apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-biz-customer-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce-biz-customer
      version: v1
  template:
    metadata:
      labels:
        app: commerce-biz-customer
        version: v1
    spec:
      containers:
        - name: commerce-biz-customer
          image: commerce-biz-customer:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10079
          env:
            - name: VERSION
              value: "v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-biz-customer-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce-biz-customer
      version: v2
  template:
    metadata:
      labels:
        app: commerce-biz-customer
        version: v2
    spec:
      containers:
        - name: commerce-biz-customer
          image: commerce-biz-customer:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10079
          env:
            - name: VERSION
              value: "v2"
---
apiVersion: v1
kind: Service
metadata:
  name: commerce-biz-customer
  labels:
    app: commerce-biz-customer
spec:
  type: ClusterIP
  ports:
    - port: 10079
      name: http
  selector:
    app: commerce-biz-customer
