version: "3.7"
services:
  commerce-redis:
    image: "redis:6.0.10-alpine"
    command: redis-server --appendonly yes
    restart: always
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4G"
    volumes:
      - redis_storage:/data
    networks:
      - redis_network

volumes:
  redis_storage:

networks:
  redis_network: